name: solar system workflow

on:
    workflow_dispatch:
    push: #triggered whenever we push to the main branch or to feature/* branch
        branches:
            - main
            - 'feature/*'
#the job without env vars failed because we need to path them here.
env: 
    MONGO_URI: 'mongodb+srv://supercluster.d83jj.mongodb.net/superData'
    MONGO_USERNAME: ${{ vars.MONGO_USERNAME }}
    MONGO_PASSWORD: ${{ secrets.MONGO_PASSWORD }}
jobs:
    unit-testing:
        name: unit testing
        services:
          mongo-db:
            image: siddharth67/mango-db:non-prod
            ports:
              - 27017:27017
        env:
          MANGO_URI: 'mangodb://localhost:27107/superData'
          MANGO_USERNAME: non-prod-username
          MANGO_PASSWORD: non-prod-password
        strategy:
            matrix:
                nodejs_version: [18, 19, 20]
                operating_system: [ubuntu-latest]
                exclude:
                    - nodejs_version: 18
                      operating_system: macos-latest
        runs-on: ${{ matrix.operating_system }}
        steps:
        - name: checkout repo
          uses: actions/checkout@v4
        
        - name: setup nodejs version - ${{ matrix.nodejs_version }}
          uses: actions/setup-node@v3
          with: #with keyword to add aditional info.
            node-version: ${{ matrix.nodejs_version }}

        - name: install dependencies
          run: npm install

        - name: unit testing
          run: npm test

        - name: archive test result
          uses: actions/upload-artifact@v4
          with:
            name: mocha-test-result-${{ matrix.nodejs_version }}-${{ matrix.operating_system }}
            path: test-results.xml
    
    code-coverage:
        name: code coverage
        container:
          image: node:18
        services:
          mongo-db:
            image: siddharth67/mango-db:non-prod
            options:
              --name mango
            #ports:
            #  - 27017:27017 #no need for port mapping bec it's container talking to another container
        env:
            MANGO_URI: 'mangodb://mango:27107/superData'
            MANGO_USERNAME: non-prod-username
            MANGO_PASSWORD: non-prod-password
        runs-on: ubuntu-latest
        steps:
            - name: checkout repo
              uses: actions/checkout@v4
            
          #  - name: setup nodejs version - 18
          #    uses: actions/setup-node@v3
          #    with:
          #      node-version: 18
            
            - name: install dependencies
              run: npm install

            - name: check code coverage
              run: npm run coverage

            - name: archive test result
              uses: actions/upload-artifact@v4
              with:
                name: code-coverage-result
                path: coverage
                retention-days: 5
    docker:
        name: containerization
        needs: [unit-testing, code-coverage]
        runs-on: ubuntu-latest
        steps:
        - name: checkout
          uses: actions/checkout@v4

        - name: Build Docker image locally
          run: |
            docker build -t local/solar-system:test .

        - name: Docker Image Test
          run: |
            docker images
            docker run --name solar-system-app -d \
              -p 3000:3000 \
              -e MANGO_URI=$MANGO_URI \
              -e MANGO_USERNAME=$MANGO_USERNAME \
              -e MANGO_PASSWORD=$MANGO_PASSWORD \
              local/solar-system:test

            export IP=$(docker inspect -f '{{range .NetworkSettings.Networks}}{{.IPAddress}}{{end}}' solar-system-app)
            echo $IP

            echo "Testing Image URL using wget"
            wget -q -O - 127.0.0.1:3000/live | grep live

    dev-deploy:
      needs: docker
      runs-on: ubuntu-latest
      steps:
        - name: checkout
          uses: actions/checkout@v4

        - name: Install kubectl CLI
          uses: azure/setup-kubectl@v4
          with:
              version: 'v1.26.0'

        - name: fetch kubernetes cluster details
          run: |
            kubectl version --short -o yaml
            echo ---------------------
            kubectl get nodes